### ISSUE TITLE
Display week ends in other color, e.g. red

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#111]

**Comment by kaklakariada** [comment]
@ckunki : Which color / color code do you prefer? https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#color_keywords

**Comment by ckunki** [comment]
They grey you chose is a nice color - not too obstrusive :)

**Comment by kaklakariada** [comment]
Thanks! I will try it out :)

**Comment by ckunki** [comment]
PR https://github.com/itsallcode/white-rabbit/pull/154

**Comment by kaklakariada** [comment]
Closed with #154
