### ISSUE TITLE
Key "escape" closes main application window

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#147]
Steps to reproduce: User selects a specific day, starts to enter time for begin and then aborts
time editing with key "escape".

Observed behavior: WR aborts times editing and closes application window.

Expected behavior: WR aborts times editing, but leaves window open.

Suggestions: Either catch event key press and to not forward to main application or disable window closing with key "escape" and replace by Alt-F4 or something else.

**Comment by kaklakariada** [comment]
I could not reproduce this. When editing the "begin" time and typing the Escape key aborts editing and the window stays visible. The window hides after typing Escape a second time.

@ckunki: Could you please check if the issue still exists?
