### ISSUE TITLE
WR refuses to add > 1 activity for days with empty begin and/or end time

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#148]
Steps to reproduce: User selects a specific day without any begin or end time. User adds activities.

Observed behavior: WR refuses to add > 1 activity.

Expected behavior: User can add arbitrary number of activities even for days with empty start and/or end time.

**Comment by kaklakariada** [comment]
I can confirm this strange behavior. We definitely need to fix this ;)
