### ISSUE TITLE
Collapse "Activities today" hides activities forever (workaround: delete ui-state.json)

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#156]
Steps to reproduce: User clicks on arrow left of "Activities today".
WR collapse lower pane with activities.

Observed behavior: When user clicks again on arrow left of "Activities today", then AR fails to show activities.
User cannot move horizontal divider. Activities remain hidden without any way for use to reveal them again. 

Expected behavior: When user clicks again on arrow left of "Activities today", then AR show activities.
User can move horizontal divider.

**Comment by kaklakariada** [comment]
This is strange. I could not reproduce it, but this is definitely a bug. In fact, the complete line should be clickable and should collapse/de-collapse the section.

Do you know additional preconditions for reproducing this?

**Comment by ckunki** [comment]
Preconditions: 
1. start WR
2. click on arrow left of "Activities today".

Sorry :(

**Comment by kaklakariada** [comment]
Can you please check the log for error messages?

**Comment by ckunki** [comment]
[white-rabbit.log](https://github.com/itsallcode/white-rabbit/files/6531715/white-rabbit.log)

... but at first glance I do not seem anything suspicious....

**Comment by kaklakariada** [comment]
It's possible that this is caused by UI-state restoring. Please rename file `C:\HOME\.whiterabbit\ui-state.json` (and keep it for reference) and try again.

Background: At shutdown, WR writes the UI state (column widths, collapse-state of the activities table etc.) to this file and restores the state at startup. See class `UiStateService`.

**Comment by ckunki** [comment]
Perfect! Thanks. 
Yes, this removed the problem. 
file `ui-state.json` attached for reference: [156-ui-state.json.txt](https://github.com/itsallcode/white-rabbit/files/6531901/156-ui-state.json.txt)

**Comment by kaklakariada** [comment]
Great, thanks for the update and for attaching the file. We can use it to debug the issue.

**Comment by kaklakariada** [comment]
Could not reproduce the issue with the attached file. Issue already solved via simple workaround.
