### ISSUE TITLE
Fix CHANGELOG.md

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#157]
Eclipse IDE complains about unresolved references in markup file CHANGELOG.md:

Cannot resolve element with id 'building_release'	CHANGELOG.md	
/white-rabbit	line 114	WikiText Markup Problem
- #configuration
- #project_config
- #optional_config
- #building_release

**Comment by ckunki** [comment]
Question to @kaklakariada: where should these references point to?

**Comment by kaklakariada** [comment]
They should point to sections in the same file. It's possible that the references are broken, but I think that the eclipse editor can't resolve the links.

If the links work in a browser they should be fine.

**Comment by ckunki** [comment]
I could not find any of these references in the file. 
Links do not work in browser, either.

**Comment by ckunki** [comment]
I found it: Links should point to file README.md :) 
And #building_release has been removed.
