### ISSUE TITLE
PmSmart: Enable skip handling comments

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#158]
Entering comments via web UI takes quite some time.

If a specific user does not use comments for recorded times at all, then WR should enable this user to configure WR to ignore all comments.

If WR ignores comments then web UI can skip transfer of comments and hence will execute faster.

**Comment by ckunki** [comment]
How about a property in `.whiterabbit.properties`? 
```
pmsmart.transfer.comments = false
```

**Comment by kaklakariada** [comment]
Sounds good to me!

**Comment by ckunki** [comment]
Is this a mandatory value?

Interface PluginConfiguration, provides only the possibility to ask the configuration for mandatory values, but not for optional ones. And in my eyes `pmsmart.transfer.comments` would rather be an optional configuration. 

Two options: 
1. enhance interface to contain a method also for optional values or create an additional interface 
2. declare option `pmsmart.transfer.comments` as mandatory in spite of my gut feelings

**Comment by kaklakariada** [comment]
Until now there was no need for optional parameters ;-). Please add a method to PluginConfiguration, returning an Optional.

**Comment by ckunki** [comment]
I added a method for optional parameters.
