### ISSUE TITLE
Search-as-you-type for activity comments

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/white-rabbit#16]
## Situation

Often you find yourself repeating the same comments in activities over and over.
A search-as-you-type approach would be nice for these comments, where either a box with the best matches opens close to the cell where the text is entered or the closest match is added in grey letters behind the text you type.

To make sure that only relevant entries remain, and that the search is fast, the search should span only two months. Two months are long enough so that extended vacations don't completely empty the search cache and short enough to get rid of outdated entries.

## Acceptance Criteria

1. Comment cell supports search-as-you-type spanning a search range of the last 60 days.

**Comment by kaklakariada** [comment]
Search-as-you-type implemented also for day comments. When creating a new activity, the most used project from the last 2 months is selected.
