### ISSUE TITLE
PM Smart export fails

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#206]
Error message: 
> Expected day 2021-07-01 selected

[white-rabbit.log](https://github.com/itsallcode/white-rabbit/files/6876633/log.log)

**Comment by ckunki** [comment]
2nd attempt was successful - hm 🤔

**Comment by ckunki** [comment]
Seems to be still an issue. 
I assume timing issues. E.g. browser takes a while to *really* select the day expected by WR.
I am thinking of a strategy like 
1. select day 
2. check if day was selected successfully and correctly 
3. if not then wait 1 second and repeat step # 2 
4. limit repetitions to a reasonable number, e.g. 3 or 5 
5. only fail if defined number of repetitions is exhausted

**Comment by kaklakariada** [comment]
The PMSmart plugin was removed in https://github.com/itsallcode/white-rabbit/pull/239 because it is not maintained any more.
