### ISSUE TITLE
Add option to configure automatic breaks

### ISSUE THREAD

**Issue by jakobbraun** [itsallcode/white-rabbit#247]
From my experience White-Rabbbit automatically adds a 45 min break after working 4 hours.
For me that does not fit, since during my break I switch off my laptop so it's allreaddy added as an interruption.
Is there an option for disabling this feature?
If not could we add it?

**Comment by kaklakariada** [comment]
@jakobbraun: I added option `mandatory_break` to the config file. Please set it to `PT0M` and check if #247 works for you.
