### ISSUE TITLE
Mind day starting time after "stop working for today"

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/white-rabbit#58]
## Situation

At the moment if you press "stop working for today", this seems to affect the next day too. The start time is not detected. Rather is is registered as "00:00".

## Expected Behavior

* Start time of next day after "stop working for today" is automatically detected

## Actual Behavior

* Start time defaults to "00:00"

## Reproducibility

100%

## Environment

* White Rabbit 1.2.0
* Fedora Linux 32
* Java 15 OpenSDK

**Comment by kaklakariada** [comment]
Looks like your computer does not go to sleep properly and wakes up at midnight. To diagnose this, please try to shut down your computer in the evening and check if the problem still exists when starting in the morning.

**Comment by kaklakariada** [comment]
Not reproducible. I assume your machine did not go to sleep and WhiteRabbit was running at 0:00, so it updated the "begin" time.
