### ISSUE TITLE
Persist cell changes on focus loss

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/white-rabbit#6]
## Situation

When entering a time and hitting TAB, I lose the value. It is only persisted if I hit ENTER before changing to a different cell

## Acceptance Criteria

* Moving away from a cell persists the cells contents

**Comment by kaklakariada** [comment]
This was also reported by @p1pp5l3r

**Comment by redcatbear** [comment]
I just realized how serious this issue is. I use focus-follows mouse. If you leave the cell by accidentally touching the mouse, your current entry gets lost.

**Comment by redcatbear** [comment]
Hitting the TAB key also triggers this issue.
