### ISSUE TITLE
"Close" time recording for month 

### ISSUE THREAD

**Issue by p1pp5l3r** [itsallcode/white-rabbit#72]
### "Close" time recording for month 

As a product owner, I would like to have the opportunity to mark months as "closed" and thus protect them against changes.

### Acceptance criteria

- It's possible to mark a month as closed
- after closing a month, this month is immutable

**Comment by kaklakariada** [comment]
WhiteRabbit uses a decentralized approach. A feature like this would require central storage. If you need this, please implement a [storage plugin](https://github.com/itsallcode/white-rabbit/blob/develop/api/src/main/java/org/itsallcode/whiterabbit/api/features/MonthDataStorage.java).
