### ISSUE TITLE
Use of white-rabbit on multiple time recording clients

### ISSUE THREAD

**Issue by p1pp5l3r** [itsallcode/white-rabbit#73]
### Use of white-rabbit on multiple time recording clients

As a product owner, I would like to have the opportunity to use white-rabbit on several time recording clients. Since I work on different computers a day I would love to have synced clients. 

### Acceptance criteria

- time  recording clients shall be in-sync 
- in case of collisions "last saved" time recording shall "win"

**Comment by kaklakariada** [comment]
This is out of scope for WhiteRabbit. If you need a feature like this, please implement a custom [storage plugin](https://github.com/itsallcode/white-rabbit/blob/develop/api/src/main/java/org/itsallcode/whiterabbit/api/features/MonthDataStorage.java).
